disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - type_name
  - nesting
  - type_body_length
  - implicitly_unwrapped_optional

opt_in_rules:
  - force_unwrapping
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - implicitly_unwrapped_optional
  - unused_import
  - toggle_bool
  - sorted_first_last
  - private_outlet
  - private_action
  - overridden_super_call
  - operator_usage_whitespace
